version: '3'
services:
  etcd0:
    image: quay.io/coreos/etcd:v3.3
    ports:
      - 2379
    volumes:
      - ./bin/tlskey:/etc/etcd/etcdSSL
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://etcd0:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://etcd0:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
      - --cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --peer-cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --peer-key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --trusted-ca-file
      - /etc/etcd/etcdSSL/etcd-root-ca.pem
      - --peer-trusted-ca-file
      - /etc/etcd/etcdSSL/etcd-root-ca.pem
  etcd1:
    image: quay.io/coreos/etcd:v3.3
    ports:
      - 2379
    volumes:
      - ./bin/tlskey:/etc/etcd/etcdSSL
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://etcd1:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://etcd1:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
      - --cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --peer-cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --peer-key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --trusted-ca-file
      - /etc/etcd/etcdSSL/etcd-root-ca.pem
      - --peer-trusted-ca-file
      - /etc/etcd/etcdSSL/etcd-root-ca.pem
  etcd2:
    image: quay.io/coreos/etcd:v3.3
    ports:
      - 2379
    volumes:
      - ./bin/tlskey:/etc/etcd/etcdSSL
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd2
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - https://etcd2:2379
      - -listen-client-urls
      - https://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - https://etcd2:2380
      - -listen-peer-urls
      - https://0.0.0.0:2380
      - -initial-cluster
      - etcd0=https://etcd0:2380,etcd1=https://etcd1:2380,etcd2=https://etcd2:2380
      - --cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --peer-cert-file
      - /etc/etcd/etcdSSL/etcd.pem
      - --peer-key-file
      - /etc/etcd/etcdSSL/etcd-key.pem
      - --trusted-ca-file
      - /etc/etcd/etcdSSL/etcd-root-ca.pem
      - --peer-trusted-ca-file
      - /etc/etcd/etcdSSL/etcd-root-ca.pem
  etcd-manage:
    # build: .
    image: "shiguanghuxian/etcd-manage:1.v2"
    ports:
      - "10280:10280"
    volumes:
      - ./bin/config/cfg.toml:/app/config/cfg.toml
      - ./bin/logs:/app/logs
      - ./bin/tlskey:/etc/etcd/etcdSSL
    depends_on:
      - etcd0
      - etcd1
      - etcd2
